language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
env: 
  movie_api_key:
    secure: "l5AbRlLh5V5gMVQN2xxY1X88w6q2s26COCSKPbQtlDm37gYIOCyz81ZVMWm2Fr07EnFulms1mRQCDDFarj87r30f8AY+drQufFyYlPAt8kssJTHG+xYG2OkEV8tq1Y1es9uuPxkudGF9/gQC1wAq0Xy1Bx84oeexfY0VC7WHx0v4N6kYLWehANFb54hrdBEGcb9duoGnXduG0RM6BDnoftwBcRK2hxSFATR68ygxcAs6LgYWuwkf1rDUUSuXY/L1R9VTK9G1jEwJmQ9Z2DVN7ospAuAQ7eIYXtG7nawGYEhwD3H+lWzdUzLgd/oIBFhoouLT014AjVqy4CM5nzsuoq9zH6x1h3lKdn4IYkNyYRj077rX+Dre1HKQlRVzcWS7KWd0kefFjI9rcYyPFi7XF/SO7z4AZC1p27XojiUvmAYl/DIptmMIeuqJ7mCfEb7xlIksHfC1MfLLYPMTanmtss2B/wCw4Q/lXBSaeeZfMtG+YvCaUiiAsJOV9i3EnWtD8UdUcQ5T2aMf/xyOXxahobM2p3pGeP6RoHVoqzE3Nr9pBtdEs32vy1HSY1F7BlYNwnrfQ/75GJ81/q2NyPidW8tXQqp3YMuLcp5opqK9JprwZJqiB1VKyP/ueKQIo7nJZ4tSHx8rvtjhEQHKSowu/eBwraoXD3EsOyGjFYRO9TU="
deploy:
  provider: heroku
  api_key:
    secure: ao88hxVvZq59YK+ftlVk64/gVt4+9VX/Qg51ZxyZrNhSsVW3p3HUPkjJoTDFoy1nhXRWJlsr8T50pbI5dUcsk8BLCDM+g7VYdbRUWIinc5Y+vYdfr4R2BDOMSBp/IS3peke2QU7/j6RlD1yF2f6uVbUfAfj726EgtkBMU3m9Jys57VNuTNb6B5QE0CYyDGftsW13UJ5tL3z0BhqF9bvuD7U84ygICE7O11CCE7OuvtKsSw+hqpyybPGLxtWRhva6NVipum8S8XX8hmGQQwoiuixh+vGYaRd5sReBkg84zf7SjYin7AtPxigK+mGRo0JVxDfdp9Qi8C9B4GDcVcIqgNOoZ7rhbyHRZroEQHRxWyXOS8FbWQRx+2egMk5CsEfcevzZdB0o9/Wr9MdkGJVwT8alCKWaSbg8GgbpEGlKwzfwq3QRTMOnp9cktjfKSRBo2wl99TcjDdhqHGSJ9iBH9A8eOV7lHFmFBNJi2Yj6DtTr31GV8PDJ/+DQ/fin3p30m4P3f42AOnPSLzx+GsC1wipm9n/+dXtaAQub4oAykN6bV4lf/PCcA14nZbKs64hCfsCJzzL5+QzKuMqLDT3RUIsmlPE585+9AD9rhqjC0fUqwO18cYXgt4JAb9cM4UDCVgVuv9t3WvZr8o9H/N3EuF4pWUYdFXZflF4I3P3X2Mo=
    app: stormy-bastion-67887
  run: rails db:migrate
  on:
    branch: main